"""Public package API for Bible IO.

The reference package is re-exported for convenience.  Its ``Book`` type is
named :class:`ReferenceBook` here so :class:`bible_io.Book` always means the
loaded content model.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError as _PackageNotFoundError
from importlib.metadata import version as _distribution_version

from bible_io_references import (
    AUTO_LANGUAGE_COLLISIONS,
    AUTO_LANGUAGE_PRECEDENCE,
    BIBLE_BOOK_IDENTIFIERS,
    BOOK_ABBREVIATIONS_BY_LANGUAGE,
    BOOK_NAMES_BY_LANGUAGE,
    DEFAULT_MAX_LOOKAHEAD,
    DEFAULT_MAX_LOOKBEHIND,
    DOCUMENTED_LANGUAGE_TERM_COLLISIONS,
    MAX_CHAPTER_NUMBER,
    MAX_LOOKAROUND,
    MAX_VERSE_NUMBER,
    MIN_LOOKAROUND,
    SUPPORTED_PARSING_LANGUAGES,
    BibleBookEnum,
    BibleLanguageEnum,
    Book as ReferenceBook,
    BookIdentifiers,
    BookNameStyle,
    BookPassage,
    ChapterPassage,
    IdentifierError,
    IdentifierErrorCode,
    IdentifierFormat,
    Language,
    LanguageTermAuditReport,
    NormalizedInput,
    ParseBibleBookError,
    ParseFailure,
    ParseResult,
    ParseSuccess,
    ParseVerseRefError,
    Parsed,
    Passage,
    PassageLabelBuilder,
    PassageMatch,
    PassageParser,
    PassageReplacement,
    PassageSequence,
    PassageUriBuilder,
    Reference,
    ReferenceAmbiguityPolicy,
    ReferenceBookCandidate,
    ReferenceBookTokenMatch,
    ReferenceExtractor,
    ReferenceFormatter,
    ReferenceParseErrorCode,
    ReferenceParseMetadata,
    ReferenceParser,
    SourceSpan,
    VersePassage,
    VerseRangeRef,
    VerseRef,
    audit_language_terms,
    book_from_osis_identifier,
    book_from_usfm_identifier,
    collapse_whitespace,
    format_passage,
    format_reference,
    normalize_for_parsing,
    normalize_reference_input,
    normalize_reference_input_detailed,
    osis_book_identifier,
    osis_identifier,
    parse_passage,
    parse_passage_detailed,
    parse_passage_result,
    parse_reference,
    parse_reference_result,
    passage_from_dict,
    reference_from_dict,
    reference_from_osis_identifier,
    reference_from_usfm_identifier,
    supported_parsing_languages,
    try_parse_reference,
    usfm_book_identifier,
    usfm_identifier,
)

from .bible_class import (
    Bible,
    BibleInitializationData,
    BiblePerformanceMetrics,
    BibleReferenceResult,
    BibleStats,
    EditionParsed,
    EditionPassage,
    EditionReference,
    EditionVerseRange,
    VerseSelection,
)
from .book import Book
from .chapter import Chapter
from .errors import (
    BibleDataFormatError,
    BibleDataFormatErrorCode,
    BibleError,
    BookNotFoundError,
    BookRef,
    ChapterNotFoundError,
    ReferenceParseError,
    VerseNotFoundError,
)
from .json_value import (
    EMPTY_JSON_OBJECT,
    DuplicateJsonKeyError,
    FrozenJsonObject,
    FrozenJsonValue,
    JsonScalar,
    JsonValue,
    decode_json_with_unique_keys,
    freeze_json_map,
    freeze_json_object,
    freeze_json_value,
    json_value_equal,
    json_value_hash,
    thaw_json_value,
    validate_json_string,
)
from .loading import (
    CURRENT_BIBLE_SCHEMA_VERSION,
    BibleDataValidationOptions,
    BibleLoadOptions,
    BibleLoadPhase,
    BibleLoadProgress,
    BibleLoadProgressCallback,
    SearchIndexMode,
)
from .location import BibleLocation, BibleVerseKey
from .result import Failure, Result, ResultException, Success
from .search import (
    BookResolver,
    SearchHit,
    SearchMode,
    SearchOptions,
    SearchResults,
    TextRange,
    find_match_ranges,
    find_search_match_ranges,
    fuzzy_match_ranges,
    fuzzy_matches,
    matches_search_text,
    search_verses,
)
from .search_index import SearchIndex, VerseLocationTuple, build_search_index
from .source import (
    BibleCatalog,
    BibleMetadata,
    BibleSource,
    TextDirectionHint,
    merge_bible_metadata,
)
from .stats import BookStats, ChapterStats, VerseStats
from .text_search import (
    SearchTextToken,
    build_search_index_terms,
    contains_normalized_text,
    extract_unicode_words,
    find_normalized_substring_ranges,
    is_within_levenshtein_distance,
    normalize_search_text,
    normalized_range_to_source,
    search_index_lookup_key,
    tokenize_search_text,
    tokenize_search_text_with_ranges,
    uses_unspaced_word_boundaries,
)
from .verse import Verse


try:
    __version__ = _distribution_version("bible-io")
except _PackageNotFoundError:  # pragma: no cover - source tree without install
    __version__ = "0+unknown"


__all__ = [
    # Bible IO content and edition values.
    "Bible",
    "BibleInitializationData",
    "BiblePerformanceMetrics",
    "BibleReferenceResult",
    "BibleStats",
    "Book",
    "BookStats",
    "Chapter",
    "ChapterStats",
    "EditionParsed",
    "EditionPassage",
    "EditionReference",
    "EditionVerseRange",
    "Verse",
    "VerseSelection",
    "VerseStats",
    # Loading, validation, metadata, catalogs, and persisted state.
    "CURRENT_BIBLE_SCHEMA_VERSION",
    "BibleCatalog",
    "BibleDataValidationOptions",
    "BibleLoadOptions",
    "BibleLoadPhase",
    "BibleLoadProgress",
    "BibleLoadProgressCallback",
    "BibleLocation",
    "BibleMetadata",
    "BibleSource",
    "BibleVerseKey",
    "SearchIndexMode",
    "TextDirectionHint",
    "merge_bible_metadata",
    # Search values, index, and reusable text utilities.
    "BookResolver",
    "SearchHit",
    "SearchIndex",
    "SearchMode",
    "SearchOptions",
    "SearchResults",
    "SearchTextToken",
    "TextRange",
    "VerseLocationTuple",
    "build_search_index",
    "build_search_index_terms",
    "contains_normalized_text",
    "extract_unicode_words",
    "find_match_ranges",
    "find_normalized_substring_ranges",
    "find_search_match_ranges",
    "fuzzy_match_ranges",
    "fuzzy_matches",
    "is_within_levenshtein_distance",
    "matches_search_text",
    "normalize_search_text",
    "normalized_range_to_source",
    "search_index_lookup_key",
    "search_verses",
    "tokenize_search_text",
    "tokenize_search_text_with_ranges",
    "uses_unspaced_word_boundaries",
    # Typed errors and non-throwing result helpers.
    "BibleDataFormatError",
    "BibleDataFormatErrorCode",
    "BibleError",
    "BookNotFoundError",
    "BookRef",
    "ChapterNotFoundError",
    "Failure",
    "ReferenceParseError",
    "Result",
    "ResultException",
    "Success",
    "VerseNotFoundError",
    # Immutable JSON extension-value helpers.
    "EMPTY_JSON_OBJECT",
    "FrozenJsonObject",
    "FrozenJsonValue",
    "JsonScalar",
    "JsonValue",
    "DuplicateJsonKeyError",
    "decode_json_with_unique_keys",
    "freeze_json_map",
    "freeze_json_object",
    "freeze_json_value",
    "json_value_equal",
    "json_value_hash",
    "thaw_json_value",
    "validate_json_string",
    # bible_io_references, with its Book type deliberately renamed.
    "AUTO_LANGUAGE_COLLISIONS",
    "AUTO_LANGUAGE_PRECEDENCE",
    "BIBLE_BOOK_IDENTIFIERS",
    "BOOK_ABBREVIATIONS_BY_LANGUAGE",
    "BOOK_NAMES_BY_LANGUAGE",
    "DEFAULT_MAX_LOOKAHEAD",
    "DEFAULT_MAX_LOOKBEHIND",
    "DOCUMENTED_LANGUAGE_TERM_COLLISIONS",
    "MAX_CHAPTER_NUMBER",
    "MAX_LOOKAROUND",
    "MAX_VERSE_NUMBER",
    "MIN_LOOKAROUND",
    "SUPPORTED_PARSING_LANGUAGES",
    "BibleBookEnum",
    "BibleLanguageEnum",
    "ReferenceBook",
    "BookIdentifiers",
    "BookNameStyle",
    "BookPassage",
    "ChapterPassage",
    "IdentifierError",
    "IdentifierErrorCode",
    "IdentifierFormat",
    "Language",
    "LanguageTermAuditReport",
    "NormalizedInput",
    "ParseBibleBookError",
    "ParseFailure",
    "ParseResult",
    "ParseSuccess",
    "ParseVerseRefError",
    "Parsed",
    "Passage",
    "PassageLabelBuilder",
    "PassageMatch",
    "PassageParser",
    "PassageReplacement",
    "PassageSequence",
    "PassageUriBuilder",
    "Reference",
    "ReferenceAmbiguityPolicy",
    "ReferenceBookCandidate",
    "ReferenceBookTokenMatch",
    "ReferenceExtractor",
    "ReferenceFormatter",
    "ReferenceParseErrorCode",
    "ReferenceParseMetadata",
    "ReferenceParser",
    "SourceSpan",
    "VersePassage",
    "VerseRangeRef",
    "VerseRef",
    "audit_language_terms",
    "book_from_osis_identifier",
    "book_from_usfm_identifier",
    "collapse_whitespace",
    "format_passage",
    "format_reference",
    "normalize_for_parsing",
    "normalize_reference_input",
    "normalize_reference_input_detailed",
    "osis_book_identifier",
    "osis_identifier",
    "parse_passage",
    "parse_passage_detailed",
    "parse_passage_result",
    "parse_reference",
    "parse_reference_result",
    "passage_from_dict",
    "reference_from_dict",
    "reference_from_osis_identifier",
    "reference_from_usfm_identifier",
    "supported_parsing_languages",
    "try_parse_reference",
    "usfm_book_identifier",
    "usfm_identifier",
    # Package metadata.
    "__version__",
]
